//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DessertApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dessert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dessert()
        {
            this.OrderLines = new HashSet<OrderLine>();
        }
    
        public int DessertID { get; set; }
        public string DessertName { get; set; }
        public int DessertTypeID { get; set; }
        public Nullable<decimal> DessertPrice { get; set; }
    
        public virtual DessertType DessertType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLines { get; set; }
    }
}
