//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DessertApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLine
    {
        public int OrderlineID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Dessert Dessert { get; set; }
        public virtual Order Order { get; set; }
    }
}
